version: "3"

# Environment variables are defined at .env

services:
  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - server_db:/var/lib/postgresql/data

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER="rabbitmq"
      - RABBITMQ_DEFAULT_PASS="rabbitmq"
    image: "rabbitmq:3"
    hostname: "rabbitmq"

    ports:
      - "5672:5672"

  common-validations:
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    image: "hbolzan/common-validations:latest"

  api:
    environment:
      - DOCKERIZED=${DOCKERIZED}
      - DJANGO_APP_PORT=${DJANGO_APP_PORT}
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - API_DB_PASS=${API_DB_PASS}
      - API_DB_NAME=${API_DB_NAME}
      - API_DB_USER=${API_DB_USER}
      - API_DB_HOST=db
      - API_DB_PORT=${API_DB_PORT}
      - DATA_DB_NAME=${DATA_DB_NAME}
      - DATA_DB_USER=${DATA_DB_USER}
      - DATA_DB_HOST=db
      - DATA_DB_PORT=${DATA_DB_PORT}
    # build: .
    image: "hbolzan/django-sql-to-rest:latest"
    volumes:
      - static_volume:/app/sql-to-rest/static
    ports:
      - "${DJANGO_APP_PORT}"
    # debugging entrypoint commented
    # entrypoint: ["sh", "-c", "sleep 2073600"]
    entrypoint: ["/docker-entrypoint.sh"]
    depends_on:
      - common-validations
      - db
      - rabbitmq

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/sql-to-rest/static
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  server_db:
  static_volume:
