version: "3"

# Environment variables are defined at .env

services:
  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - server_db:/var/lib/postgresql/data

  nameko-rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    image: "rabbitmq:3-management"
    hostname: "nameko-rabbitmq"
    ports:
      - "15672:15672"
      - "5672"

  # services
  common-validations:
    environment:
      - RABBIT_HOST=nameko-rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=rabbitmq
      - RABBIT_PASSWORD=rabbitmq
    image: "hbolzan/common-validations:latest"
    depends_on:
      - nameko-rabbitmq

  # main application
  api:
    environment:
      - DOCKERIZED=${DOCKERIZED}
      - DJANGO_APP_PORT=${DJANGO_APP_PORT}
      - RABBIT_HOST=nameko-rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=rabbitmq
      - RABBIT_PASSWORD=rabbitmq
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - API_DB_PASS=${API_DB_PASS}
      - API_DB_NAME=${API_DB_NAME}
      - API_DB_USER=${API_DB_USER}
      - API_DB_HOST=db
      - API_DB_PORT=${API_DB_PORT}
      - DATA_DB_NAME=${DATA_DB_NAME}
      - DATA_DB_USER=${DATA_DB_USER}
      - DATA_DB_HOST=db
      - DATA_DB_PORT=${DATA_DB_PORT}
    # build: .
    image: "hbolzan/django-sql-to-rest:latest"
    volumes:
      - static_volume:/app/sql-to-rest/static
    ports:
      - "${DJANGO_APP_PORT}"
    # debugging entrypoint - uncomment to debug
    # entrypoint: ["sh", "-c", "sleep 2073600"]
    depends_on:
      - common-validations
      - db
      - nameko-rabbitmq

  # remove frontend_volume after rebuilding frontend image
  # frontend
  metaforms:
    image: "hbolzan/metaforms-static:latest"
    volumes:
      - frontend_volume:/html

  # nginx
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/sql-to-rest/static
      - frontend_volume:/app/metaforms/html
    ports:
      - 1337:80
    depends_on:
      - api
      - metaforms

volumes:
  server_db:
  static_volume:
  frontend_volume:
