version: "3"
services:
  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - server_db:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3"
    hostname: "nameko-rabbitmq"
    ports:
      - "5672:5672"

  api:
    environment:
      - DOCKERIZED=${DOCKERIZED}
      - DJANGO_APP_PORT=${DJANGO_APP_PORT}
      - API_DB_PASS=${API_DB_PASS}
      - API_DB_NAME=${API_DB_NAME}
      - API_DB_USER=${API_DB_USER}
      - API_DB_HOST=db
      - API_DB_PORT=${API_DB_PORT}
      - DATA_DB_NAME=${DATA_DB_NAME}
      - DATA_DB_USER=${DATA_DB_USER}
      - DATA_DB_HOST=db
      - DATA_DB_PORT=${DATA_DB_PORT}
    # build: .
    image: "hbolzan/django-sql-to-rest:test-02"
    ports:
      - "8000:8000"
    # debugging entrypoint commented
    # entrypoint: ["sh", "-c", "sleep 2073600"]
    entrypoint: ["/docker-entrypoint.sh"]
    depends_on:
      - db
      - rabbitmq

volumes:
  server_db:
