# Generated by Django 2.1.7 on 2019-04-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalidation',
            name='before_validate',
            field=models.TextField(blank=True, help_text='Actions to apply to arguments before validation', null=True, verbose_name='Before validate'),
        ),
    ]
