# Generated by Django 2.1.4 on 2019-01-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentQuery',
            fields=[
                ('name', models.CharField(max_length=80, verbose_name='Query name')),
                ('query_id', models.SlugField(blank=True, max_length=80, primary_key=True, serialize=False, verbose_name='Query ID')),
                ('insert_pk', models.CharField(blank=True, help_text='Inform insert table pk field to allow retrieving last inserted row', max_length=255, null=True, verbose_name='Insert PK')),
                ('query_pk', models.CharField(blank=True, help_text='Inform query pk qualified field to allow retrieving last inserted row', max_length=255, null=True, verbose_name='Query PK')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('sql_query', models.TextField(blank=True, null=True, verbose_name='SQL Query')),
                ('sql_insert', models.TextField(blank=True, null=True, verbose_name='SQL Insert')),
                ('sql_update', models.TextField(blank=True, null=True, verbose_name='SQL Update')),
                ('sql_delete', models.TextField(blank=True, null=True, verbose_name='SQL Delete')),
            ],
            options={
                'verbose_name': 'Persistent query',
                'verbose_name_plural': 'Persistent queries',
            },
        ),
    ]
