# Generated by Django 2.1.5 on 2019-01-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentNestedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(help_text='Name of attribute that will receive nested result', max_length=100, verbose_name='Attribute name')),
                ('related_field', models.CharField(help_text='Name of field related to parent PK', max_length=100, verbose_name='Related fiedl')),
            ],
        ),
        migrations.AlterField(
            model_name='persistentquery',
            name='insert_pk',
            field=models.CharField(blank=True, help_text='Inform insert table pk field, qualified with table and schema, to allow retrieving last inserted row', max_length=255, null=True, verbose_name='Insert PK'),
        ),
        migrations.AddField(
            model_name='persistentnestedquery',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_query', to='db_query.PersistentQuery', verbose_name='Child query'),
        ),
        migrations.AddField(
            model_name='persistentnestedquery',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_query', to='db_query.PersistentQuery', verbose_name='Parent query'),
        ),
    ]
