# Generated by Django 2.1.5 on 2019-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0002_auto_20190125_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentnestedquery',
            name='related_field',
            field=models.CharField(help_text='Name of field related to parent PK', max_length=100, verbose_name='Related field'),
        ),
    ]
