# Generated by Django 2.1.7 on 2019-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0004_auto_20190125_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentquery',
            name='conn_name',
            field=models.CharField(blank=True, help_text='Specify connection name (blank = query_db)', max_length=255, null=True, verbose_name='Connection name'),
        ),
    ]
