# Generated by Django 2.1.11 on 2019-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0006_auto_20190708_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistentquery',
            name='sql_search_where',
            field=models.TextField(blank=True, null=True, verbose_name='SQL search where'),
        ),
        migrations.AlterField(
            model_name='persistentquery',
            name='sql_query',
            field=models.TextField(blank=True, null=True, verbose_name='SQL base query'),
        ),
    ]
