# Generated by Django 2.1.7 on 2019-06-29 21:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('route', models.CharField(blank=True, max_length=255, null=True, verbose_name='Route')),
                ('scopes', models.CharField(blank=True, help_text='Access scopes separeted by commas', max_length=255, null=True, verbose_name='Scopes')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.SystemMenu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
