# Generated by Django 2.1.7 on 2019-06-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmenu',
            name='separator',
            field=models.BooleanField(default=False, verbose_name='Separator'),
        ),
    ]
